### ISSUE TITLE
Disco - A fresh look at DI

### ISSUE THREAD

**Issue by shochdoerfer** [php-usergroup-dresden/slides#16]
In this session let me introduce you to [Disco](https://github.com/bitexpert/disco), a container-interop compatible, annotation-based Dependency Injection container. Disco does not use an external configuration file but uses a standard PHP class with some meta data attached to configure your services. I will guide you through the journey of setting up Disco for a new project as well as highlighting its main features. Join me for a fun little ride to "DI done right" land!

**Comment by shochdoerfer** [comment]
Slides und erstes Feedback findet sich auf [joind.in](https://joind.in/event/phpugffm-v2016/disco).

**Comment by hollodotme** [comment]
Danke noch einmal Stephan.
