### ISSUE TITLE
[April 2017 meetup talk] Use Coding Standards like Professional under 5 minutes 

### ISSUE THREAD

**Issue by TomasVotruba** [php-usergroup-dresden/slides#19]
Hey, we're trying to reach other local communities. This week we've been to [Berlin meetup](http://www.bephpug.de/2017/04/04/april.html), where we found out, there are also PHP meetups in Dresden. That's a reason to make a trip there :)

As told by @tommy-muehle, I'm writing here.

I love topic of the meetup and have simple code quality tool to introduce.

**I'd like to have a short 5min talk** about tool for analysis of coding standard, that combines PhpCodeSniffer and PHPCsFixer and is easy to without knowledge of any of them - [EasyCodingStandard](https://github.com/Symplify/EasyCodingStandard).

**Comment by hollodotme** [comment]
* Announced on [meetup.com](https://www.meetup.com/PHP-USERGROUP-DRESDEN/events/238473452/)
* Announced in [google event calendar](https://calendar.google.com/calendar/embed?src=phpugdd%40gmail.com&ctz=Europe/Berlin)
* Announced on our [website](http://phpug-dresden.org/events.html#next-event)
* Tweet scheduled for April, 11th - 10:00am

**Comment by TomasVotruba** [comment]
Thank you!

**Comment by hollodotme** [comment]
Thank you again Tomas! Was great to have you here.

**Comment by TomasVotruba** [comment]
@hollodotme Thanks for having us! I envy guys from Dresden group such to have such a great leader :+1:
