### ISSUE TITLE
API Platform

### ISSUE THREAD

**Issue by fjogeleit** [php-usergroup-dresden/slides#24]
Das Frontend unabhängig vom Backend zu entwickeln wird immer mehr gängige Praxis. Ein einfacher Weg Daten zwischen beiden Systemen auszutauschen sind REST APIs. Leider kann schon die Erstellung einfacher CRUD APIs Zeitraubend sein. Gängige Probleme sind die Erstellung eines Objektes inkl. Relationen, die Validierung, Filterung von Listen und die Reduzierung von Properties die Angezeigt werden. Für All diese Standard Probleme bietet API Platform in Symfony Projekten Abhilfe.

Im Vortrag soll diese Lösung vorgestellt werden, von der Installation zur Lösung oben genannten Probleme und weiterer benefits die helfen deutlich Zeit und Nerven zu sparen.

Dauer ca. 40min.

**Comment by hollodotme** [comment]
Event is announced on:
* [Meetup.com](https://www.meetup.com/PHP-USERGROUP-DRESDEN/events/244169435/)
* [Our website](http://phpug-dresden.org/events.html#next-event)
* [joind.in](https://joind.in/talk/099e4) - Please claim your talk for feedback.
* In the google calendar (https://calendar.google.com/calendar/embed?src=phpugdd%40gmail.com&ctz=Europe/Berlin)

**Comment by hollodotme** [comment]
Slides were uploaded here: https://speakerdeck.com/moveelevator/api-platform

Thanks @fjogeleit for the talk. Looking forward to your next one!
