### ISSUE TITLE
Event-Sourcing with CQRS - or - How to build rock solid, rocket fast web applications

### ISSUE THREAD

**Issue by hollodotme** [php-usergroup-dresden/slides#7]
## Series 1 - Einführung
- The Big Picture.
- Was ist Event Sourcing?
- Was ist CQRS?
- Warum ergänzen sich beide so gut?
- Für welche Anwendungsfälle ist es geeignet und für welche nicht?
- Beispiele aus der Praxis.
## Series 2 - Implementieren der ES Komponenten
- Was ist eine AggregateRoot?
- Was ist ein Event?
- Was ist ein EventBus?
- Was ist das Actor Model?
- Was ist ein EventStore?
- Serializer und/oder Hydratoren?
- Replaying Events
## Series 3 - ES integrieren mit CQRS
- Datenmodelle für die Schreib- und Lese-Seite (SQL / NO-SQL)
- Performance-Potenziale aufzeigen
- Beispiele aus der Praxis
- Wrap Up zur Series

**Comment by ronnyhartenstein** [comment]
@hollodotme Did you gave the speech?

**Comment by hollodotme** [comment]
Nope. :-/ Never had the time for it.
